export enum RequestKeys {
  CreateQuiz = 'create_quiz',
  DeleteQuiz = 'delete_quiz',
  GetQuizes = 'get_quizes',
  GetQuiz = 'get_quiz',
  PatchQuiz = 'patch_quiz',
  CreateSection = 'create_section',
  GetSections = 'get_sections',
  GetSection = 'get_section',
  DeleteSection = 'delete_section',
  SortSections = 'sort_sections',
  PatchSection = 'patch_section',
  GetQuestions = 'get_questions',
  CreateQuestion = 'CreateQuestion',
  DeleteQuestion = 'DeleteQuestion',
  GetQuestion = 'get_question',
  PatchQuestion = 'PatchQuestion',
  SortQuestions = 'SortQuestions',
}
